name: Manual Dependency Submission

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  submit-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate and Submit Dependency Snapshot
        uses: actions/dependency-submission-action@v5
        with:
          manifest-path: './requirements.txt'
